# Generated by Django 2.0.1 on 2018-01-20 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_subscribed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed_on',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
