# Generated by Django 2.0.1 on 2018-01-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='access_list',
        ),
    ]
