# Generated by Django 2.0.1 on 2018-01-15 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='access_list',
            field=models.ManyToManyField(related_name='shared_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
