# Generated by Django 2.0.1 on 2018-01-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_remove_task_access_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_settings',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
